"""
Realistic but entirely fictional demo data for a mid-sized retail/commercial bank.

~18 models with a deliberate mix of traditional ML (scorecards, IFRS 9, fraud,
AML, stress testing) and generative / LLM systems (chatbot, summarisers,
classifiers, extraction). Dates are computed relative to *today* so the
overdue / due-soon states always demo correctly, whenever you run it.
"""

from __future__ import annotations

from datetime import date, timedelta
from typing import Any

from validation_llm import DEFAULT_CHATBOT_SYSTEM_PROMPT


def _months_ago(n: int) -> str:
    today = date.today()
    month_index = today.month - 1 - n
    year = today.year + month_index // 12
    month = month_index % 12 + 1
    day = min(today.day, 28)
    return date(year, month, day).isoformat()


def _days_from_now(n: int) -> str:
    return (date.today() + timedelta(days=n)).isoformat()


def build_models() -> list[dict[str, Any]]:
    M = "Traditional ML"
    G = "Generative AI / LLM"
    models: list[dict[str, Any]] = [
        {
            "id": "MR-001",
            "name": "Retail Application Scorecard (PD)",
            "owner": "Priya Nair, Retail Credit Risk",
            "business_area": "Credit Risk",
            "purpose": "Approve/decline decisioning and probability-of-default for new retail loan applications.",
            "methodology": "Logistic-regression scorecard (WOE-binned).",
            "family": M,
            "vendor": "In-house",
            "status": "Production",
            "go_live_date": _months_ago(40),
            "last_validation_date": _months_ago(9),
            "ratings": {"materiality": 3, "explainability": 1, "autonomy": 2,
                        "output_variability": 1, "drift": 2, "data_quality": 2, "fairness_bias": 3},
        },
        {
            "id": "MR-002",
            "name": "Behavioural Scorecard — Credit Cards",
            "owner": "Tom Okafor, Cards Risk",
            "business_area": "Credit Risk",
            "purpose": "Monthly behavioural PD used for limit management and provisioning inputs.",
            "methodology": "Gradient-boosted trees (XGBoost).",
            "family": M,
            "vendor": "In-house",
            "status": "Production",
            "go_live_date": _months_ago(33),
            "last_validation_date": _months_ago(22),
            "ratings": {"materiality": 2, "explainability": 2, "autonomy": 2,
                        "output_variability": 1, "drift": 3, "data_quality": 2, "fairness_bias": 2},
        },
        {
            "id": "MR-003",
            "name": "IFRS 9 ECL Model Suite",
            "owner": "Sarah Bennett, Finance",
            "business_area": "Finance / Credit Risk",
            "purpose": "PD/LGD/EAD term-structure models driving expected credit loss provisions.",
            "methodology": "Econometric PD/LGD/EAD with macroeconomic overlays.",
            "family": M,
            "vendor": "In-house",
            "status": "Production",
            "go_live_date": _months_ago(58),
            "last_validation_date": _months_ago(26),
            "ratings": {"materiality": 3, "explainability": 2, "autonomy": 1,
                        "output_variability": 1, "drift": 3, "data_quality": 2, "fairness_bias": 1},
        },
        {
            "id": "MR-004",
            "name": "Mortgage PD & Affordability Model",
            "owner": "Priya Nair, Retail Credit Risk",
            "business_area": "Credit Risk",
            "purpose": "Default risk and affordability assessment for residential mortgage applications.",
            "methodology": "Logistic regression with policy rules.",
            "family": M,
            "vendor": "In-house",
            "status": "Production",
            "go_live_date": _months_ago(45),
            "last_validation_date": _months_ago(11),
            "ratings": {"materiality": 3, "explainability": 1, "autonomy": 2,
                        "output_variability": 1, "drift": 2, "data_quality": 2, "fairness_bias": 3},
        },
        {
            "id": "MR-005",
            "name": "SME Credit Risk Rating",
            "owner": "Daniel Hughes, Commercial Risk",
            "business_area": "Credit Risk",
            "purpose": "Internal risk grade for small & medium enterprise lending.",
            "methodology": "Gradient-boosted trees on bureau + financials.",
            "family": M,
            "vendor": "Vendor",
            "status": "Production",
            "go_live_date": _months_ago(30),
            "last_validation_date": _months_ago(25),
            "ratings": {"materiality": 2, "explainability": 2, "autonomy": 2,
                        "output_variability": 1, "drift": 2, "data_quality": 3, "fairness_bias": 2},
        },
        {
            "id": "MR-006",
            "name": "Card Fraud Detection (real-time)",
            "owner": "Lena Fischer, Financial Crime",
            "business_area": "Fraud / Financial Crime",
            "purpose": "Real-time authorisation scoring; auto-declines or steps up suspected fraudulent transactions.",
            "methodology": "Gradient-boosting + neural-net ensemble.",
            "family": M,
            "vendor": "Vendor",
            "status": "Production",
            "go_live_date": _months_ago(28),
            "last_validation_date": _months_ago(10),
            "ratings": {"materiality": 3, "explainability": 3, "autonomy": 3,
                        "output_variability": 2, "drift": 3, "data_quality": 2, "fairness_bias": 2},
        },
        {
            "id": "MR-007",
            "name": "AML Transaction Monitoring",
            "owner": "Lena Fischer, Financial Crime",
            "business_area": "Financial Crime",
            "purpose": "Generates suspicious-activity alerts on customer transaction behaviour.",
            "methodology": "Rules engine + supervised alert-prioritisation ML.",
            "family": M,
            "vendor": "In-house",
            "status": "Production",
            "go_live_date": _months_ago(50),
            "last_validation_date": _months_ago(26),
            "ratings": {"materiality": 3, "explainability": 2, "autonomy": 2,
                        "output_variability": 1, "drift": 3, "data_quality": 2, "fairness_bias": 2},
        },
        {
            "id": "MR-008",
            "name": "Regulatory Stress Testing (ICAAP)",
            "owner": "Sarah Bennett, Finance",
            "business_area": "Finance",
            "purpose": "Scenario-based capital and loss projection for ICAAP and regulatory stress tests.",
            "methodology": "Econometric / scenario expansion models.",
            "family": M,
            "vendor": "In-house",
            "status": "Production",
            "go_live_date": _months_ago(60),
            "last_validation_date": _months_ago(14),
            "ratings": {"materiality": 3, "explainability": 2, "autonomy": 1,
                        "output_variability": 1, "drift": 2, "data_quality": 2, "fairness_bias": 1},
        },
        {
            "id": "MR-009",
            "name": "Customer Churn Propensity",
            "owner": "Maya Roberts, Marketing Analytics",
            "business_area": "Marketing",
            "purpose": "Ranks customers by likelihood to attrite for retention campaigns.",
            "methodology": "Random forest.",
            "family": M,
            "vendor": "In-house",
            "status": "Production",
            "go_live_date": _months_ago(24),
            "last_validation_date": _months_ago(20),
            "ratings": {"materiality": 1, "explainability": 2, "autonomy": 1,
                        "output_variability": 1, "drift": 2, "data_quality": 2, "fairness_bias": 1},
        },
        {
            "id": "MR-010",
            "name": "Collections Prioritisation",
            "owner": "Daniel Hughes, Collections",
            "business_area": "Credit Risk / Operations",
            "purpose": "Prioritises delinquent accounts for collections treatment.",
            "methodology": "Gradient-boosted trees.",
            "family": M,
            "vendor": "In-house",
            "status": "Production",
            "go_live_date": _months_ago(27),
            "last_validation_date": _months_ago(15),
            "ratings": {"materiality": 2, "explainability": 2, "autonomy": 2,
                        "output_variability": 1, "drift": 2, "data_quality": 2, "fairness_bias": 2},
        },
        {
            "id": "MR-011",
            "name": "Market Risk VaR",
            "owner": "Akira Tanaka, Market Risk",
            "business_area": "Market Risk",
            "purpose": "Value-at-Risk for the trading book.",
            "methodology": "Historical simulation.",
            "family": M,
            "vendor": "In-house",
            "status": "Production",
            "go_live_date": _months_ago(52),
            "last_validation_date": _months_ago(13),
            "ratings": {"materiality": 3, "explainability": 2, "autonomy": 1,
                        "output_variability": 2, "drift": 2, "data_quality": 2, "fairness_bias": 1},
        },
        # ── Generative AI / LLM ────────────────────────────────────────────────
        {
            "id": "MR-012",
            "name": "Customer Service Chatbot — NorthBank Assistant",
            "owner": "Maya Roberts, Customer Operations",
            "business_area": "Retail / Customer Operations",
            "purpose": "Customer-facing assistant answering retail banking questions and guiding self-service.",
            "methodology": "Large language model with retrieval and a defined system prompt / guardrails.",
            "family": G,
            "vendor": "Vendor LLM (API)",
            "status": "Production",
            "go_live_date": _months_ago(8),
            "last_validation_date": _months_ago(5),
            "ratings": {"materiality": 3, "explainability": 3, "autonomy": 2,
                        "output_variability": 3, "drift": 2, "data_quality": 2, "fairness_bias": 2,
                        "hallucination": 3, "prompt_injection": 3},
            "system_prompt": DEFAULT_CHATBOT_SYSTEM_PROMPT,
            "llm_last_run": None,
        },
        {
            "id": "MR-013",
            "name": "Credit Memo Summariser",
            "owner": "Daniel Hughes, Commercial Lending",
            "business_area": "Commercial Lending",
            "purpose": "Drafts summaries of credit files to speed up credit-committee preparation (human-reviewed).",
            "methodology": "LLM summarisation over internal documents.",
            "family": G,
            "vendor": "In-house (LLM API)",
            "status": "Production",
            "go_live_date": _months_ago(10),
            "last_validation_date": _months_ago(13),
            "ratings": {"materiality": 2, "explainability": 3, "autonomy": 1,
                        "output_variability": 3, "drift": 1, "data_quality": 2, "fairness_bias": 1,
                        "hallucination": 3, "prompt_injection": 2},
            "system_prompt": None,
            "llm_last_run": None,
        },
        {
            "id": "MR-014",
            "name": "Complaints Classifier",
            "owner": "Maya Roberts, Customer Operations",
            "business_area": "Customer Operations / Compliance",
            "purpose": "Categorises and routes inbound complaints; flags potential vulnerability and FCA reportability.",
            "methodology": "LLM classification.",
            "family": G,
            "vendor": "In-house (LLM API)",
            "status": "Production",
            "go_live_date": _months_ago(15),
            "last_validation_date": _months_ago(26),
            "ratings": {"materiality": 2, "explainability": 3, "autonomy": 2,
                        "output_variability": 2, "drift": 2, "data_quality": 2, "fairness_bias": 2,
                        "hallucination": 2, "prompt_injection": 2},
            "system_prompt": None,
            "llm_last_run": None,
        },
        {
            "id": "MR-015",
            "name": "KYC Document Extraction",
            "owner": "Lena Fischer, Onboarding / Financial Crime",
            "business_area": "Financial Crime / Onboarding",
            "purpose": "Extracts identity and address fields from customer-supplied onboarding documents.",
            "methodology": "LLM + OCR extraction pipeline.",
            "family": G,
            "vendor": "Vendor",
            "status": "Production",
            "go_live_date": _months_ago(12),
            "last_validation_date": _months_ago(11),
            "ratings": {"materiality": 3, "explainability": 3, "autonomy": 2,
                        "output_variability": 2, "drift": 2, "data_quality": 3, "fairness_bias": 2,
                        "hallucination": 3, "prompt_injection": 3},
            "system_prompt": None,
            "llm_last_run": None,
        },
        {
            "id": "MR-016",
            "name": "Marketing Content Generator",
            "owner": "Maya Roberts, Marketing",
            "business_area": "Marketing",
            "purpose": "Drafts marketing copy and email campaigns (subject to human sign-off and compliance review).",
            "methodology": "LLM generation.",
            "family": G,
            "vendor": "Vendor",
            "status": "Development",
            "go_live_date": "",
            "last_validation_date": "",
            "ratings": {"materiality": 1, "explainability": 3, "autonomy": 1,
                        "output_variability": 3, "drift": 1, "data_quality": 1, "fairness_bias": 2,
                        "hallucination": 3, "prompt_injection": 1},
            "system_prompt": None,
            "llm_last_run": None,
        },
        {
            "id": "MR-017",
            "name": "Internal Policy Q&A Assistant (RAG)",
            "owner": "Sarah Bennett, Compliance",
            "business_area": "Compliance / Knowledge",
            "purpose": "Answers staff questions on internal policies and procedures from approved documents.",
            "methodology": "Retrieval-augmented LLM over a policy knowledge base.",
            "family": G,
            "vendor": "In-house (LLM API)",
            "status": "Production",
            "go_live_date": _months_ago(16),
            "last_validation_date": _months_ago(18),
            "ratings": {"materiality": 1, "explainability": 3, "autonomy": 1,
                        "output_variability": 2, "drift": 1, "data_quality": 2, "fairness_bias": 1,
                        "hallucination": 2, "prompt_injection": 2},
            "system_prompt": None,
            "llm_last_run": None,
        },
        {
            "id": "MR-018",
            "name": "Call Transcript QA & Summarisation",
            "owner": "Maya Roberts, Customer Operations",
            "business_area": "Customer Operations / Compliance",
            "purpose": "Summarises and quality-scores contact-centre call transcripts for QA sampling.",
            "methodology": "LLM summarisation and rubric scoring.",
            "family": G,
            "vendor": "Vendor",
            "status": "In Validation",
            "go_live_date": "",
            "last_validation_date": _months_ago(23),
            "ratings": {"materiality": 2, "explainability": 3, "autonomy": 1,
                        "output_variability": 3, "drift": 2, "data_quality": 2, "fairness_bias": 2,
                        "hallucination": 3, "prompt_injection": 2},
            "system_prompt": None,
            "llm_last_run": None,
        },
    ]
    return models


def build_findings() -> list[dict[str, Any]]:
    return [
        {
            "id": "F-001", "model_id": "MR-012",
            "title": "Jailbreak resistance gap under role-play prompts",
            "description": "Chatbot can be induced to disclose elements of its internal instructions when asked to 'act as' a developer/debugging assistant.",
            "source": "Validation", "severity": "High", "owner": "Maya Roberts",
            "raised_date": _months_ago(2), "target_date": _days_from_now(-10), "status": "Open",
        },
        {
            "id": "F-002", "model_id": "MR-012",
            "title": "Occasional over-refusal of benign product questions",
            "description": "Refusal calibration testing shows the assistant declines some harmless product questions (e.g. 'what is an overdraft?').",
            "source": "Validation", "severity": "Medium", "owner": "Maya Roberts",
            "raised_date": _months_ago(2), "target_date": _days_from_now(30), "status": "Open",
        },
        {
            "id": "F-003", "model_id": "MR-006",
            "title": "Adverse-action explainability documentation incomplete",
            "description": "Reason codes for auto-declined transactions are not consistently documented for the ensemble model.",
            "source": "Validation", "severity": "High", "owner": "Lena Fischer",
            "raised_date": _months_ago(4), "target_date": _days_from_now(-25), "status": "In Progress",
        },
        {
            "id": "F-004", "model_id": "MR-007",
            "title": "Revalidation overdue; monitoring stale",
            "description": "Model has not been revalidated within its policy frequency and ongoing performance monitoring has lapsed.",
            "source": "Internal Audit", "severity": "High", "owner": "Lena Fischer",
            "raised_date": _months_ago(1), "target_date": _days_from_now(20), "status": "Open",
        },
        {
            "id": "F-005", "model_id": "MR-003",
            "title": "ECL macroeconomic overlay lacks formal back-testing",
            "description": "Management overlays on the ECL output are not subject to a documented back-testing process.",
            "source": "Validation", "severity": "Medium", "owner": "Sarah Bennett",
            "raised_date": _months_ago(3), "target_date": _days_from_now(45), "status": "Open",
        },
        {
            "id": "F-006", "model_id": "MR-015",
            "title": "No prompt-injection testing on document-ingestion path",
            "description": "The pipeline ingests untrusted customer-supplied documents but has not been tested for prompt-injection via document contents.",
            "source": "Validation", "severity": "High", "owner": "Lena Fischer",
            "raised_date": _months_ago(2), "target_date": _days_from_now(-5), "status": "Open",
        },
        {
            "id": "F-007", "model_id": "MR-001",
            "title": "Disparate-impact ratio near four-fifths threshold",
            "description": "One subgroup's selection-rate ratio sits just above 0.80; requires monitoring and root-cause review.",
            "source": "Validation", "severity": "Medium", "owner": "Priya Nair",
            "raised_date": _months_ago(2), "target_date": _days_from_now(60), "status": "Open",
        },
        {
            "id": "F-008", "model_id": "MR-005",
            "title": "Vendor documentation incomplete (training-data lineage)",
            "description": "Vendor has not provided sufficient documentation of training-data sources and representativeness.",
            "source": "Validation", "severity": "Medium", "owner": "Daniel Hughes",
            "raised_date": _months_ago(5), "target_date": _days_from_now(-40), "status": "In Progress",
        },
        {
            "id": "F-009", "model_id": "MR-013",
            "title": "Groundedness sampling rate below recommended level",
            "description": "Ongoing groundedness/hallucination sampling covers fewer summaries than the monitoring standard requires.",
            "source": "Ongoing Monitoring", "severity": "Low", "owner": "Daniel Hughes",
            "raised_date": _months_ago(1), "target_date": _days_from_now(75), "status": "Open",
        },
        {
            "id": "F-010", "model_id": "MR-014",
            "title": "Drift monitoring not automated",
            "description": "Population/label drift is checked manually each quarter rather than through an automated monitor.",
            "source": "Validation", "severity": "Medium", "owner": "Maya Roberts",
            "raised_date": _months_ago(3), "target_date": _days_from_now(15), "status": "Open",
        },
        {
            "id": "F-011", "model_id": "MR-018",
            "title": "Reference answer set too small for quality scoring",
            "description": "The known-good reference set used for quality evaluation is too small to draw robust conclusions.",
            "source": "Validation", "severity": "Medium", "owner": "Maya Roberts",
            "raised_date": _months_ago(1), "target_date": _days_from_now(50), "status": "Open",
        },
        {
            "id": "F-012", "model_id": "MR-011",
            "title": "Backtesting exceptions documentation outdated",
            "description": "VaR backtesting exception log has not been refreshed for the latest period.",
            "source": "Ongoing Monitoring", "severity": "Low", "owner": "Akira Tanaka",
            "raised_date": _months_ago(2), "target_date": _days_from_now(-3), "status": "Closed",
        },
    ]
